version: '3.7'

services:

  youtubefilter-frontend:
    container_name: youtubefilter-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      # - '/usr/src/app/node_modules'
    stdin_open: true
    tty: true
    environment:
    - HOST=0.0.0.0
    - CHOKIDAR_USEPOLLING=true
    ports:
      - '8080:8080'
    

networks:
  default: 
    external: true
    name: net